### ISSUE TITLE
Publish on JCenter and Maven Central

### ISSUE THREAD

**Issue by renatoathaydes** [dialex/JCDP#3]
Hi! Great job with this library.

Is there any reason why you don't publish the library on JCenter or Maven Central?

If you need help with that, let me know... I usually publish on Bintray's JCenter, which is fairly simple, and recently started using its automatic push to Maven Central which simplifies life a lot and lets people using Maven to get your lib without adding any repositories.

**Comment by clun** [comment]
+1 your library will be more visible in Maven Central. 

You already have a pull request available to mavenize everything. Now I really to not know how I can easy use it in my OSS project I don't want to "copy" or fork you work, still I need to publish.

Let us know is you need some backup to publish to the central. I did all the process with FF4J.

**Comment by jjob3ci** [comment]
yep this is a great library and should be published on mvn central

**Comment by dialex** [comment]
I'm so sorry for the delay. Just to let you need that I started today publishing this library to Maven and Gradle. I'll let you know if I need your assistance. I will also look at the current pull requests. It's the first time I do this 😜

**Comment by dialex** [comment]
@renatoathaydes @clun 
Have you heard of JitPack? @xafero mentioned it on his pull request, and it looks a lot easier than using maven central. Thoughts?

**Comment by renatoathaydes** [comment]
@dialex JitPack works only with GitHub projects... it's not a centralized binaries repository in the sense that it does not distribute binaries, it just checks out source using git then builds it and adds it as a project dependency (a lot of projects cannot be built without some setup, so this is not ideal for all projects).

It works in some cases, but to make it easy for any Java developer to use this project, it should be on Maven Central in my opinion (so it works with any Java build tool).

As I said before, I would advise you to start by adding the project to JCenter (which will already make it much easier to use it), which is very simple from the Bintray website... once you've done that, if you have the patience to request a groupId you can use to publish to Maven Central with Sonatype, then Bintray will be able to [automatically publish](https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html) it for you on Maven Central.

**Comment by dialex** [comment]
I published this repo on Maven Central at http://repo1.maven.org/maven2/com/diogonunes/JCDP/
You can also search for it at http://search.maven.org/

However, I tried adding a dependency on my `pom.xml`, but my IDE (IntelliJ) could not find the source. See below:
<img width="914" alt="screen shot 2016-09-20 at 20 01 33" src="https://cloud.githubusercontent.com/assets/2140450/18702965/df9d2cea-7fdb-11e6-8916-fa300718db10.png">

I also went to the IDE configurations, **Maven > Repositories** and updated the repo (for some reason it was never updated). But that didn't solve the issue either.
<img width="878" alt="screen shot 2016-09-20 at 20 27 33" src="https://cloud.githubusercontent.com/assets/2140450/18702966/dfadec1a-7fdb-11e6-8922-81f4045a7590.png">

However when I went to the project's libraries, the IDE was able to find it and add it as a dependency. But the `pom.xml` was not changed.
![screen shot 2016-09-21 at 09 23 34](https://cloud.githubusercontent.com/assets/2140450/18703278/1f690668-7fdd-11e6-9f2d-55e6e024d0ca.png)

@renatoathaydes @clun 
**What should I place on the `pom` so that everyone is able to download the library?**

**Comment by dialex** [comment]
Looks like its done! Somehow.

Apparently when searching for `JCDP`, IntelliJ doesn't find it, but if I search for `diogo` it does... because reasons.

I'm planning to release this big update (v2.0) this next weekend. Thanks for your patience.

**Comment by renatoathaydes** [comment]
It was probably that the IntelliJ index does not update for a while. I checked your artifacts in Maven Central and they seem to be correct, except for this:

``` xml
<name>${project.groupId}:${project.artifactId}</name>
```

**Comment by renatoathaydes** [comment]
Oh, it seems that your dependency on Hamcrest is not scoped as `test`. Is Hamcrest used by the library?

**Comment by dialex** [comment]
Regarding `<name>${project.groupId}:${project.artifactId}</name>`... I copied that from a Maven tutorial. Is uses the variables of the POM itself. So far it worked, why do you say it is wrong?

Regarding Hamcrest... I think you're right, the library doesn't use it, it's just for testing purposes. How do I mark it as test only?

**Comment by renatoathaydes** [comment]
like this: https://github.com/dialex/JCDP/blob/master/pom.xml#L139

**Comment by dialex** [comment]
Thanks @renatoathaydes, I fixed it on v2.0.1 (also released on Maven Central).
Let me know if you guys find any new issues.

I also added some fancy Shields to this repo, namely Travis CI.
So now changes are reviewed by the unit tests (and code analysis, via Codacy) 😀🎉
