### ISSUE TITLE
Debugging Output in Eclipse IDE Does not format the markup

### ISSUE THREAD

**Issue by krebznet** [dialex/JCDP#47]
Hello, 
I believe this is a limitation of the eclipse console but when I'm trying to build an app using JCDP the output in the console shows up something like the snippet below. Does anyone know if there is a workaround to seeing your formatted output in a IDE without having to build/export the compiled jar of my app every-time? Thanks. - Krebznet

[37;44mColoredPrinter | level: 0 | timestamping: false | Attribute: NONE | Foreground color: WHITE | Background color: BLUE[0m
[37;44mThis printer will always format text with WHITE font on BLUE background.[0m
[7;37;44mFrom now on, that format is reversed.[0m
ColoredPrinters do not affect System.* format.
[7;37;44mEven if[0m you mix [7;37;44mthe two.[0m
[33m2020-06-09 12:29:15 This printer displays timestamps and warning messages.[0m
[36m2020-06-09 12:29:15 And this printer can be used for info messages.[0m
[mThis example used JCDP 4.0.0   [0m[1;33;42m	MADE [0m[1;33;41mIN PORTUGAL[0m
[mI hope you find it useful ;)[0m

**Comment by dialex** [comment]
Hey Duncan!
I suspect that's because Eclipse's terminal doesn't support ANSI codes. There's not much I can do, because this implements uses the standard ANSI codes. This is a limitation of Eclipse.

I googled a bit and there's more people with your issue on Eclipse, even for other libs like Jansi. Several users recommended this ["ANSI Escape in Console"](https://marketplace.eclipse.org/content/ansi-escape-console) extension. I found fewer references to this [other extension](http://mihai-nita.net/2013/06/03/eclipse-plugin-ansi-in-console/).

As an alternative you can start using IntelliJ Community Edition (which is also free/open) 😏 😏 

I hope this helps you solve the issue 😉
