### ISSUE TITLE
Feature: Support of clear screen

### ISSUE THREAD

**Issue by OllisGit** [dialex/JCDP#56]
First: Thx, a lot for this nice toolkit!!!!

Sometimes I want to start with a clear screen and the ANSI support this feature:
see: https://en.wikipedia.org/wiki/ANSI_escape_code (look for ```Erase in Display```)
```
	StringBuilder clearScreenEscBuilder = new StringBuilder();
        char c = 27;
        char c2 = '[';
        clearScreenEscBuilder.append(c);
        clearScreenEscBuilder.append(c2);
        clearScreenEscBuilder.append("2");
        clearScreenEscBuilder.append("J");
		
        String clear = clearScreenEscBuilder.toString();
        String text = "[34mMy Super Duper blue text on a clear screen[0m";
        System.out.println(clear);
        System.out.println(text);
```

What do you think?

BR
Olli

**Comment by dialex** [comment]
Done 😉
It will be included in JColor 5.1.0. I'll try to push the new release now, otherwise check next Saturday.

The syntax is `colorize(CLEAR_SCREEN())`, so your example becomes:

```java
String text = "�[34mMy Super Duper blue text on a clear screen�[0m";
System.out.println(colorize(CLEAR_TEXT()));
System.out.println(text);
```

Even though `CLEAR_SCREEN()` is an `Ansi.Command` and not an `Ansi.Attribute` I decided to maintain the `colorized()` syntax and avoid creating a new method.

_Sidenote: I also gave `H` a try ([source](https://stackoverflow.com/a/37778152/675577)) but the results were incorrect. It actualy deleted the lines previously printed. The `2J` simply pushes the previous lines up by adding new empty lines._

`H` output
<img width="1536" alt="H" src="https://user-images.githubusercontent.com/2140450/119272585-87d67c00-bbfe-11eb-94e3-97a4d7f1db5c.png">

`2J` output
<img width="1536" alt="2J" src="https://user-images.githubusercontent.com/2140450/119272582-8442f500-bbfe-11eb-985f-699d7e5641fa.png">

**Comment by dialex** [comment]
Update: I'll release this feature on May 29, as I recently switched laptops and I don't have the right setup to release now

**Comment by dialex** [comment]
Just deployed it to Maven Central. The new version (`5.1.0`) still doesn't appear listed there, as it usually takes a while (hours). Feel free to update your dependencies file for the new version and check if it can pull the latest version. If not, you'll have to wait :)

**Comment by OllisGit** [comment]
Thx, a lot. Works as expected.
```
System.out.println( colorize( Command.CLEAR_SCREEN() ));
```
It is currently not listed in mvn, but this is not a big deal, because I am already using jitpack.io as an additional repo-proxy against github.

```
	<repositories>
		<!-- Used for private GitHub-Repositories. Needed for JColor -->
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
...
		<dependency>
			<groupId>com.github.dialex</groupId>
			<artifactId>JColor</artifactId>
			<version>v5.1.0</version>
		</dependency>
```
