### ISSUE TITLE
feature request: remove the jna dependency

### ISSUE THREAD

**Issue by PiprTuff** [dialex/JCDP#67]
The JNA dependency is now redundant. It should be removed.

**Comment by dialex** [comment]
For future reference, (as I keep returning to this issue and forget what's the current state), here's some context.

The `JNA` dependency was introduced because of [this](https://github.com/dialex/JColor/issues/25#issuecomment-568200617): Windows 10 users assumed JColor didn't work, but in fact it was a [limitation](https://github.com/PowerShell/PowerShell/issues/11449) of Windows. The `JNA` allowed us to change a Windows default without the user noticing, so that JColor works as expected.

Later on, [I decided to stop doing that for the users](https://github.com/dialex/JColor/issues/62), so that I could remove the `JNA` dependency and keep this library lean. So now Windows 10 users already have to fix this by themselves, and [I made a detailed list of workarounds and instructions](https://github.com/dialex/JColor/issues/62#issuecomment-967010670).

At this point, the only thing missing is removing the dependency, because the code that used that dependency was already removed. I'll create a PR to clean that up once and for all.

Thanks for reminding me about this 😉
